### ISSUE TITLE
Pre model download

### ISSUE THREAD

**Issue by tjulitianyi1997** [peteryuX/retinaface-tf2#1]
Hello, your pre-model is on Google Drive, I cannot download it, can you upload it to Baidu hard drive or send it to my mailbox? Thank you very much and I wish you good health.
E-mail  1375088614@qq.com

**Comment by tjulitianyi1997** [comment]
如果您能直接提供.pb模型就更好了。

**Comment by peteryuX** [comment]
Sorry for the late reply! But I cannot suseccsfully rigsist the account for using Baidu hard disk... And the models is too big to send by email...

**Comment by tjulitianyi1997** [comment]
Thanks, my foreign friends already send it to me by Tencent QQ. Anyway, thank you very much. I plan to port your project to an embedded device, but if I encounter some problems, can I still consult you? Or you can add my WeChat, you can search 15620620950, it will be fine. Or add my QQ 1375088614. Thank you. Tianyi Li 邮箱：tjulitianyi1997@gmail.com 签名由 网易邮箱大师 定制 On 04/07/2020 19:30, Kuan-Yu Huang wrote: Sorry for the late reply! But I cannot suseccsfully rigsist the account for using Baidu hard disk... And the models is too big to send by email... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by peteryuX** [comment]
Sounds great @tjulitianyi1997 ! You can contact me with email (provided on my [page](https://peteryux.github.io/)) for any discussion you need! About the porting things, I think converting it to tf-lite with weights quantization would be a great option. Good luck for you and have a good day!
