### ISSUE TITLE
Inference with TF1.15

### ISSUE THREAD

**Issue by ilyanelken** [peteryuX/retinaface-tf2#17]
Hello, first of all thanks for this impressive code for training.
I want to ask if there is a way to run models trained with this code with TF1.15 instead TF2?
Thanks,
Ilya

**Comment by zhjikoshlizhzc** [comment]
Hello,Ilya.
Whether you have successfully implemented the model transformation？
Could you please provide the lower version of the model that you successfully converted and can successfully predict? Thank you very much.

**Comment by suraj-maniyar** [comment]
Hello @ilyanelken & @zhjikoshlizhzc 
If you could provide any information on running inference from this model under TF1.x, it would be much appreciated.
Thanks.
