### ISSUE TITLE
Runtime performance

### ISSUE THREAD

**Issue by p-hofer** [peteryuX/retinaface-tf2#2]
First things first: many thanks for the nice tensorflow2 implementation! I used your pre-trained model on my laptop (with my webcam) and I am getting ~1 FPS. How many FPS do you achieve? Have you tried to convert it to Tensorflow Light yet? Do you have other ideas of how to make it run faster (i.e. get more FPS)?

**Comment by peteryuX** [comment]
Hi @p-hofer ,
Thanks for asking~ Even run on the GTX1080ti the speed performance also is quite slow (\~6 FPS, 640 x 480 without any downscale). I did a little try on converting it to TF-Lite before, but some operator cannot successfully be converted directly(mainly like NMS). The subtitle idea I think to make it faster is that convert it to TF-lite version(without NMS) and do post-quantization(weithts float32 -> uint8), then rewrite a C/C++ version of NMS to produce the final results. Hope this answer would be helpful to you\~ Have a good day!
