### ISSUE TITLE
tf.checkpoint how to convert to pb correct

### ISSUE THREAD

**Issue by JustinLJun** [peteryuX/retinaface-tf2#4]
Thanks for this great work, but i convert ckpt to pb& tflite something error.

**Comment by JustinLJun** [comment]
This is my code:
        # init
	os.environ['TF_CPP_MIN_LOG_LEVEL'] = '4'
	os.environ['CUDA_VISIBLE_DEVICES'] = FLAGS.gpu

	checkpoint_dir = './checkpoints_jx/retinaface_mbv2'

	cfg = load_yaml(FLAGS.cfg_path)

	# define network
	model = RetinaFaceModel(cfg, training=True)
	model.summary(line_length=80)

	# load checkpoint
	checkpoint = tf.train.Checkpoint(model=model)
	manager = tf.train.CheckpointManager(checkpoint=checkpoint,
											directory=checkpoint_dir,
											max_to_keep=3)

	print("manager.latest_checkpoint:", manager.latest_checkpoint)
	checkpoint.restore(manager.latest_checkpoint)
	tf.saved_model.save(checkpoint, checkpoint_dir+'/pb')

**Comment by JustinLJun** [comment]
![image](https://user-images.githubusercontent.com/29404823/79446828-78572d80-8011-11ea-921c-6122d8772704.png)
pb model is unnormal.

**Comment by peteryuX** [comment]
Hi @JustinLJun~ I use `tf.keras.models.load_model()` to convert pb file and it went well (I checked from the `model.sumary()`). But showed out the wierd ghraph in the Netron visualization which is same with yours. Does the Netron really support tf2 operator right now?

**Comment by JustinLJun** [comment]
Thanks for ur answer~ so if use tf.keras.models.save_model, I should to convert CKPT to  PB first, and code like this:
hdf5_model = tf.keras.models.load_model("./model/savemodel")
converter = tf.lite.TFLiteConverter.from_keras_model(hdf5_model)
tflite_model = converter.convert()
open("retinaface.tflite", "wb").write(tflite_model)

it is right?

**Comment by JustinLJun** [comment]
I can not use tf.keras.models.save_model save model, is my Tensorflow  version problem?  
![image](https://user-images.githubusercontent.com/29404823/79524318-c52f1880-8092-11ea-8714-c8ced5a5291c.png)
![image](https://user-images.githubusercontent.com/29404823/79524342-d1b37100-8092-11ea-9ae6-6c9818d3427e.png)
Thanks for ur help~

**Comment by JustinLJun** [comment]
can you provide your "tf.train.checkpoit" model convert to "tflite"  code with me? i can convert other model,but can not convert  RetinaFaceModel.    Thanks @peteryuX

**Comment by peteryuX** [comment]
Hi @JustinLJun~ I didn't convert tflite successfully yet. I had tried it once and found there had some operators cannot be converted directly (mainly like NMS). Sorry about the lack information I can provide for this right now.

**Comment by peteryuX** [comment]
> I can not use tf.keras.models.save_model save model, is my Tensorflow version problem?
> ![image](https://user-images.githubusercontent.com/29404823/79524318-c52f1880-8092-11ea-8714-c8ced5a5291c.png)
> ![image](https://user-images.githubusercontent.com/29404823/79524342-d1b37100-8092-11ea-9ae6-6c9818d3427e.png)
> Thanks for ur help~
It should be tf.keras.models.save_model(model, "filepath_you_want")

**Comment by ma7555** [comment]
I get this error if trying to save to h5
```
    raise NotImplementedError('Layer %s has arguments in `__init__` and '
NotImplementedError: Layer FPN has arguments in `__init__` and therefore must override `get_config`.
```

saving to SavedModel format works but can not load the model..
