### ISSUE TITLE
ValueError: Received incompatible tensor with shape (1, 1, 32, 64) when attempting to restore variable with shape (1, 1, 192, 64) and name model/layer_with_weights-1/output1/conv/kernel/.ATTRIBUTES/VARIABLE_VALUE.

### ISSUE THREAD

**Issue by HamDan1999** [peteryuX/retinaface-tf2#44]
Hi
Thanks for the great work, res50 is working just fine with me but mbv2 is not working and it keeps giving me this error:
(Note that I followed the same steps as in ReadMe.
ValueError: Received incompatible tensor with shape (1, 1, 32, 64) when attempting to restore variable with shape (1, 1, 192, 64) and name model/layer_with_weights-1/output1/conv/kernel/.ATTRIBUTES/VARIABLE_VALUE.

**Comment by Belinda-great** [comment]
Hi I have the same problem.
Have you solved the problem?
I've tried and failed to find a solution, and I've been upset about it for days.
@peteryuX Could you help me?
Thank you!

**Comment by Belinda-great** [comment]
Hi @peteryuX,
I load retinaface_mbv2 model, use this model as latest_checkpoint, and use default parameters for train, when try checkpoint.restore(manager.latest_checkpoint), there have the error. ValueError: Received incompatible tensor with shape (1, 1, 32, 64) when attempting to restore variable with shape (1, 1, 192, 64).

**Comment by KafCoppelia** [comment]
Same problem

**Comment by HamDan1999** [comment]
Sorry for the late response.

I actually did not fix the error, I shifted to another repos such as:
https://github.com/biubug6/Pytorch_Retinaface
https://github.com/serengil/retinaface

**Comment by KafCoppelia** [comment]
Thank you for your reply and these two alternatives.
