### ISSUE TITLE
can not find esrgan.yaml and --save_image in test.py

### ISSUE THREAD

**Issue by FelixZhang7** [peteryuX/retinaface-tf2#5]
# Test ResNet50 backbone model
python test.py --cfg_path="./configs/esrgan.yaml" --save_image=True
# or
# Test ResNet50 backbone model
python test.py --cfg_path="./configs/psnr.yaml" --save_image=True

**Comment by peteryuX** [comment]
@FelixZhang7  I think you used the wrong command... You want to run [esrgan-tf2](https://github.com/peteryuX/esrgan-tf2) right?

**Comment by peteryuX** [comment]
Hi @FelixZhang7 , I apologize for my mistake about wrong typing on the testing command for WIDER FACE dataset. I had corrected it. Thanks a lot!!!!
