### ISSUE TITLE
Size mismatch error which running mobilenet model

### ISSUE THREAD

**Issue by Siddharth1698** [peteryuX/retinaface-tf2#50]
ValueError: Received incompatible tensor with shape (1, 1, 32, 64) when attempting to restore variable with shape (1, 1, 192, 64) and name model/layer_with_weights-1/output1/conv/kernel/.ATTRIBUTES/VARIABLE_VALUE.

**Comment by Siddharth1698** [comment]
Got it working when changed version of tf to 2.3.3.

**Comment by fisakhan** [comment]
I face a similar problem using TensorFlow: 2.15.0

ValueError: Received incompatible tensor with shape (1, 1, 32, 64) when attempting to restore variable with shape (1, 1, 192, 64) and name FPN/ConvBN/conv/kernel:0.

How can I solve this problem without downgrading to TensorFlow 2.3 ?
