### ISSUE TITLE
hard negative mining

### ISSUE THREAD

**Issue by lovejing0306** [peteryuX/retinaface-tf2#6]
请问这里为什么要做两次sort？
```
loss_class_idx = tf.argsort(loss_class, axis=1, direction='DESCENDING')
loss_class_idx_rank = tf.argsort(loss_class_idx, axis=1)
```

**Comment by peteryuX** [comment]
因為這邊我要拿到每個element的rank，下面以numpy做解釋：

np.argsort([5,2,1,4])
array([2, 1, 3, 0], dtype=int64)

np.argsort(np.argsort([5,2,1,4]))
array([3, 1, 0, 2], dtype=int64)  #  <- rank of each element

**Comment by lovejing0306** [comment]
明白了，多谢。
