### ISSUE TITLE
URL fetch failed

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [peteryuX/retinaface-tf2#8]
I am getting this error while run the code.
Exception: URL fetch failure on https://github.com/JonathanCMitchell/mobilenet_v2_keras/releases/download/v1.1/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5: None -- [Errno -2] Name or service not known

Please help.

**Comment by peteryuX** [comment]
Hi @SURABHI-GUPTA , It seems wierd~

Can you run the scripts bellow well in your colab notebook?
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/peteryuX/retinaface-tf2/blob/master/notebooks/colab-github-demo.ipynb)
